### ISSUE TITLE
Possible bug with building?

### ISSUE THREAD

**Issue by Anderzenn** [itschip/fivem-react-webpack5#1]
Hello!
I love this boilerplate a lot, it's been really useful, however I seem to be having issues when I build for the server, where it's as if my CSS isn't included at all.

This is what it looks like when I use yarn serve:
![image](https://user-images.githubusercontent.com/12025450/117701227-476f0b00-b1c7-11eb-84e4-43b9c8595180.png)

And this is what it looks like when I use yarn build:
![image](https://user-images.githubusercontent.com/12025450/117701340-68cff700-b1c7-11eb-9ebc-8a91694baa18.png)

If it's helpful, then the stylesheet file in the CSS folder looks to have JavaScript in it instead of CSS?
It looks like this: 
![image](https://user-images.githubusercontent.com/12025450/117701583-b482a080-b1c7-11eb-873f-785c8104ec10.png)

**Comment by LiamDormon** [comment]
I also have this issue, works fine in browser with `yarn serve` but when I build I get this

**Comment by itschip** [comment]
Thanks for the issue. Seems to be I mistake a made in the webpack. I will fix this tomorrow and share how to fix it so you can apply it right away!

**Comment by Anderzenn** [comment]
Awesome thank you very much!

**Comment by itschip** [comment]
> Awesome thank you very much!

Actually @Anderzenn  do you have a webpack.prod.js file?

Edit: If you have it, can you show me your package.json? I pushed what I assumed was a fix for compiling css 16 days ago, don't know when you cloned the repo.

**Comment by Anderzenn** [comment]
> > Awesome thank you very much!
> 
> Actually @Anderzenn do you have a webpack.prod.js file?

Yes, I have the one that came with the boilerplate
~~This is the code in it~~ 
Scratch that, Githubs code insert didn't like that lol. It's the same as what's in here

**Comment by itschip** [comment]
Oh okey, so it does actually create a css folder for you?

**Comment by Anderzenn** [comment]
Yeah, it makes a css folder, also makes a .css file, but the stuff inside of the .css file is javascript.

I found that if I replaced the CSS part of the prod.js with the CSS part from the dev.js, then it would work when built. But I don't know if that would cause any other issues?

**Comment by itschip** [comment]
Oh wow, I was not aware of that it created js code. I'll fix it tomorrow :) thanks again

**Comment by Anderzenn** [comment]
No problem!

**Comment by itschip** [comment]
Hi, sorry for the delay. Will be fixed within the hour,

**Comment by itschip** [comment]
@Anderzenn  @Mojito-Fivem This is fixed now, here how.

NOTE: This is for webpack.prod.js

1. Install `mini-css-extract-plugin`: `yarn add --dev mini-css-extract-plugin`
2. Configure the webpack


Replace the current test for css with this
```js
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

//...

{
  test: /\.css$/i,
  use: [MiniCssExtractPlugin.loader, 'css-loader'],
  exclude: /node_modules/,
  },
{
    test: /\.css$/i,
    use: [MiniCssExtractPlugin.loader, 'css-loader'],
    include: /node_modules/,
}

//...

plugins: [
//...
new MiniCssExtractPlugin()
]

**Comment by Anderzenn** [comment]
> @Anderzenn @Mojito-Fivem This is fixed now, here how.
> 
> NOTE: This is for webpack.prod.js
> 
> 1. Install `mini-css-extract-plugin`: `yarn add --dev mini-css-extract-plugin`
> 2. Configure the webpack
> 
> Replace the current test for css with this
> 
> ```js
> const MiniCssExtractPlugin = require('mini-css-extract-plugin');
> 
> //...
> 
> {
>   test: /\.css$/i,
>   use: [MiniCssExtractPlugin.loader, 'css-loader'],
>   exclude: /node_modules/,
>   },
> {
>     test: /\.css$/i,
>     use: [MiniCssExtractPlugin.loader, 'css-loader'],
>     include: /node_modules/,
> }
> 
> //...
> 
> plugins: [
> //...
> new MiniCssExtractPlugin()
> ]
> ```

Awesome! Thank you very much :)

**Comment by itschip** [comment]
Let me know if it works properly, so I can close this issue :)

**Comment by LiamDormon** [comment]
Seems to work

**Comment by Anderzenn** [comment]
> Let me know if it works properly, so I can close this issue :)

Yup! It works now. Thank you!
